# Generated by Django 5.1 on 2024-08-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(upload_to='cv/'),
        ),
    ]
