# Generated by Django 5.1 on 2024-08-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cloth', 'Cloth'), ('Watch', 'Watch')], default='Cloth', max_length=50),
        ),
    ]
