# Generated by Django 5.1 on 2024-08-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cloth', 'Cloth'), ('watch', 'Watch'), ('footwear', 'Footwear'), ('electronics', 'Electronics'), ('bags', 'Bags')], default=None, max_length=50),
        ),
    ]
